
echo '# ---------------------------------------------------------------------------'
echo '#   Bash shortcuts'
echo '#                                         '
echo '#   commands:       bash- unix-           '
echo '#   help:           man manwin tldr navi  '
echo '#   find:           fd fzf qfind googler lynx'
echo '#   directory:      ranger nnn tree cd    '
echo '#   list files:     ls                    '
echo '#   print:          cat bat'
echo '#   processes:      btm htop ps- top-     '
echo '#   disk use:       du df ncdu            '
echo '#   open files:     lsof                  '
echo '#   paths:          path                  '
echo '#   node:           nvm npm yarn          '
echo '#   fun:            cmatrix spark bastet task'
echo '#  ---------------------------------------------------------------------------'