print '---------------------------------------------------------------------'
print 'SYS:  paths ftp ssh brew filesys utils functs fish calc/bc'
print 'MAINT all: periodic permisssions apps status;  ncdu; mas'
print 'NET   ports ipinfo'
print 'DEV   node-info | r-info | anaconda | brew | services list/start/stop'
print 'FUN   sl cowsay fortune rev cmatrix toilet espeak  '
print '---------------------------------------------------------------------'
